name: voicewebapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_auth: ^3.1.3
  shared_preferences: ^2.0.8
  google_sign_in: ^5.1.1
  speech_to_text: ^5.1.1
  get_cli: ^1.6.0
  get: 4.3.8
  cached_network_image: ^3.1.0
  avatar_glow: ^2.0.1
  flutter_screenutil: 5.0.0+2
  logger: ^1.1.0
  cloud_firestore: ^3.1.7
  google_fonts: ^2.2.0
  flutter_sound: ^9.1.1
  http: ^0.13.4

  flutter:
    sdk: flutter
  r_dart_library: 0.4.0-nullsafety.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/fruit.jpg
  - assets/images/voice_c.png
  - assets/images/
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  fonts:
  - assets/fonts
